### ISSUE TITLE
AlwaysOnKotlin tests fail even with older checkouts

### ISSUE THREAD

**Issue by yschimke** [android/wear-os-samples#219] opened 2022-02-21 17:43 UTC
```
java.lang.IllegalStateException: No compose views found in the app. Is your Activity resumed?
	at androidx.compose.ui.test.TestContext.getAllSemanticsNodes$ui_test_release(TestOwner.kt:96)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNodes$ui_test_release(SemanticsNodeInteraction.kt:79)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:145)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:96)
```

Screen shows

![image](https://user-images.githubusercontent.com/231923/155004422-67fa0b38-cd85-4cf3-b885-db3ed7c3ff66.png)

This is both at head but also back at https://github.com/android/wear-os-samples/commit/15fdaf1a05300f9e1335b1451f81d90ac9a4a5d0

cc @alexvanyo @shumelchyk

**Comment by yschimke** [comment] 2022-02-21 17:53
Working fine for me locally on API 28.

**Comment by yschimke** [comment] 2022-02-21 17:55
Failing differently on API 26

```
com.example.android.wearable.wear.alwayson.AlwaysOnAppTests > textIsCorrectAfterReturningToActiveMode[test(AVD) - 8.0.0] FAILED 
	java.lang.AssertionError: Failed to assert the following: (Text + EditableText = [Draw count: 9])
	Semantics of the node:
Tests on test(AVD) - 8.0.0 failed: There was 1 failure(s).
Feb 21, 2022 4:56:34 PM com.google.testing.platform.RunnerImpl$Companion summarizeAndLogTestResult
SEVERE: Execute com.example.android.wearable.wear.alwayson.AlwaysOnAppTests.textIsCorrectAfterReturningToActiveMode: FAILED
java.lang.AssertionError: java.lang.AssertionError: Failed to assert the following: (Text + EditableText = [Draw count: 9])
Semantics of the node:
Node #35 at (l=75.0, t=170.0, r=205.0, b=199.0)px, Tag: 'drawCount'
Text = '[Draw count: 8]'
Actions = [GetTextLayoutResult]
Has 4 siblings
Selector used: (TestTag = 'drawCount')

at androidx.compose.ui.test.AssertionsKt.assert(Assertions.kt:270)
at androidx.compose.ui.test.AssertionsKt.assert$default(Assertions.kt:260)
at androidx.compose.ui.test.AssertionsKt.assertTextEquals(Assertions.kt:190)
at androidx.compose.ui.test.AssertionsKt.assertTextEquals$default(Assertions.kt:186)
```

**Comment by castedmo** [comment] 2022-02-22 15:00
So the issue is that the current emulator binary sets the wear emulator to be connected to a charger. This causes the charger experience to cover the whole screen whenever the display goes to ambient. 
The long term solution is to wait for a fix that is will be released which sets the wear emulator to not be on a charger by default.
The short term solution is to disconnect the charger before the test with `adb emu power ac off`

**Comment by yschimke** [comment] 2022-02-24 18:15
Running locally it generally works but there are still some timing issues or behavior change in the emulator breaking the test. Also in the compose test.

It will need someone to investigate and confirm the new behavior is a bug, or update the tests to be more tolerant if it's new expected behavior.

**Comment by kul3r4** [comment] 2024-12-03 11:31
Closing this as AlwaysOn has been deprecated.

**Closed by kul3r4** 2024-12-03 11:31 UTC
