### ISSUE TITLE
ChannelClient Example

### ISSUE THREAD

**Issue by ljunquera** [android/wear-os-samples#89] opened 2021-05-24 14:58 UTC
I wanted to use the ChannelClient to send a file and additional information (string/int information) bundled with it to a wearable. The ChannelClient seemed best for it as: 1) [it saves disk space over the DataClient](https://developer.android.com/training/wearables/data/data-layer#send-and-sync-with-API) 2) from the wearable perspective, it is not exclusive to Android phones 3) [the MessageClient does not guarantee delivery](https://developer.android.com/training/wearables/data/messages#DeliverMessage).

I can only find 2 incomplete examples of the wearable sending to the phone and both seem to use deprecated methods (GoogleApiClient and ChannelApi.OpenChannelResult). Can you add a ChannelClient example to this?

**Comment by alexvanyo** [comment] 2022-01-20 01:40
Closing as duplicate of #31

**Closed by alexvanyo** 2022-01-20 01:40 UTC
Labels: duplicate

**Comment by LouisCAD** [comment] 2022-01-22 18:56
@alexvanyo Can you also provide an update in #31? It was reported 3 years ago and didn't get a response yet.

**Comment by tberghuis** [comment] 2023-05-21 21:49
I used ChannelClient in my open source app Wrist Recorder, to send recording files from watch to phone.
https://github.com/tberghuis/WristRecorder
